_target_: skill_generator.models.skill_generator.SkillGenerator
defaults:
  - action_encoder: default
  - action_decoder: deterministic
  - prior_locator: prior_locator
  - optimizer: adam
  - lr_scheduler: constant
_recursive_: false

skill_dim: 15
skill_len: 5
kl_beta: ${loss.kl_beta}
kl_sigma: ${loss.kl_sigma}
prior_seeking_mode: 2
magic_scale: [1.2, 1.3, 1.0]
prior_locator_weight: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2, 0.2]